// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// .env.local holds real credentials (gitignored); .env only has placeholders.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI schema operations (db push/migrate/studio) use the direct
    // connection — the transaction-mode pooler (DATABASE_URL) is for app
    // runtime only and doesn't reliably support DDL operations.
    url: process.env.DIRECT_URL!,
  },
});
